explore_node:
  ros__parameters:
    costmap_topic: /bot_1/global_costmap/costmap
    costmap_updates_topic: /bot_1/global_costmap/costmap_updates
    gain_scale: 1.0
    min_frontier_size: 0.5
    orientation_scale: 0.0
    planner_frequency: 0.15
    potential_scale: 3.0
    progress_timeout: 30.0
    robot_base_frame: bot_1/base_link
    transform_tolerance: 0.3
    visualize: true
