image_width: 640
image_height: 480
camera_name: pi_camera
camera_matrix:
  rows: 3
  cols: 3
  data: [501.39729,   0.     , 315.43596,
           0.     , 499.81892, 232.04706,
           0.     ,   0.     ,   1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [0.147004, -0.256822, -0.003018, -0.000727, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [509.63544,   0.     , 314.26702,   0.     ,
           0.     , 509.3299 , 230.43516,   0.     ,
           0.     ,   0.     ,   1.     ,   0.     ]
